### ISSUE TITLE
hannemann / BLE-Remote-Companion

### ISSUE THREAD

**Issue by Nelus82** [hannemann/grid#1]
Sorry for doing this tru this github.

I really like your BLE remote companion, have it on a ESP32 to control my shield over websocket.
Is it possible to add hardware support for WT32-ETH01 so we can eliminate latency over wifi?

**Comment by hannemann** [comment]
Sorry for the inconvenience. Dont know why the issues were disabled.

Please refer to https://github.com/hannemann/BLE-Remote-Companion/issues/1
